name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
commitish: main
version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
  minor:
    labels:
      - 'minor'
      - 'enhancement'
  patch:
    labels:
      - 'patch'
      - 'fix'
      - 'bugfix'
  default: patch
  initial-version: 0.1.0
categories:
  - title: '🚀 Features'
    labels:
      - 'enhancement'
      - 'minor'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'patch'
  - title: '💥 Breaking Changes'
    labels:
      - 'breaking'
      - 'major'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
version-template: '$MAJOR.$MINOR.$PATCH'
template: |
  ## Changes
  $CHANGES 